import { BlogPost } from '../models';

export const MOCK_BLOG_POSTS: BlogPost[] = [
  {
    id: 'blog-1', title: 'How to Set Up Your First Aquarium', slug: 'how-to-set-up-your-first-aquarium',
    description: 'A step-by-step walkthrough for a stress-free first setup, from substrate to your first fish.',
    content: 'Setting up your first aquarium starts with choosing the right size tank for your space and goals. Rinse substrate and hardscape before adding them, fill with dechlorinated water, and install your filter and heater before anything else. Let the tank run for a few days to stabilize temperature, then begin cycling before adding fish.',
    image: 'https://images.unsplash.com/photo-1522069169874-c58ec4b76be5?w=1200&q=80',
    category: 'Getting Started', author: 'Maya Chen', publishedDate: '2026-01-05', status: 'Published',
    tags: ['beginner', 'setup'],
  },
  {
    id: 'blog-2', title: 'Understanding the Nitrogen Cycle', slug: 'understanding-the-nitrogen-cycle',
    description: 'Why "cycling" your tank matters and how to do it safely before adding fish.',
    content: 'The nitrogen cycle converts toxic ammonia from fish waste into nitrite, then into far less harmful nitrate. Beneficial bacteria that perform this conversion take several weeks to establish, which is why patience before fully stocking a new tank prevents "new tank syndrome" and fish loss.',
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1200&q=80',
    category: 'Water Quality', author: 'Dr. Owen Reyes', publishedDate: '2026-01-12', status: 'Published',
    tags: ['cycling', 'water-quality'],
  },
  {
    id: 'blog-3', title: 'How Often Should You Feed Your Fish?', slug: 'how-often-should-you-feed-your-fish',
    description: 'Overfeeding is the most common beginner mistake — here is how to get portions right.',
    content: 'Most tropical fish do well with small portions once or twice a day, eaten completely within two minutes. Uneaten food breaks down and spikes ammonia, so it is safer to underfeed slightly than overfeed. Consider a weekly fasting day to mimic natural feeding patterns.',
    image: 'https://images.unsplash.com/photo-1596797882870-8c33deeaaa8e?w=1200&q=80',
    category: 'Feeding', author: 'Maya Chen', publishedDate: '2026-01-19', status: 'Published',
    tags: ['feeding', 'care'],
  },
  {
    id: 'blog-4', title: 'A Beginner\u2019s Guide to Fish Compatibility', slug: 'beginners-guide-to-fish-compatibility',
    description: 'Which species get along, and which combinations to avoid in a community tank.',
    content: 'Compatibility depends on temperament, size, and water parameter needs. Peaceful schoolers like Neon Tetras and Corydoras mix well together, while fin-nippers or territorial cichlids need more careful planning. Always research adult size, not just the size at purchase.',
    image: 'https://images.unsplash.com/photo-1524704796725-9fc3044a58b2?w=1200&q=80',
    category: 'Fish Care', author: 'Priya Nair', publishedDate: '2026-01-26', status: 'Published',
    tags: ['compatibility', 'community-tank'],
  },
  {
    id: 'blog-5', title: 'Cleaning Your Aquarium Without Stressing Your Fish', slug: 'cleaning-your-aquarium-without-stressing-fish',
    description: 'A gentle, effective routine for weekly and monthly aquarium maintenance.',
    content: 'Weekly partial water changes of 10-20% remove waste without disturbing beneficial bacteria. Vacuum the substrate gently, rinse filter media in removed tank water (never tap water), and avoid scrubbing every surface at once — a partially undisturbed biofilm keeps your cycle stable.',
    image: 'https://images.unsplash.com/photo-1584967911318-3ce0dd6f4ca0?w=1200&q=80',
    category: 'Maintenance', author: 'Dr. Owen Reyes', publishedDate: '2026-02-02', status: 'Published',
    tags: ['maintenance', 'water-change'],
  },
  {
    id: 'blog-6', title: 'Choosing the Right Light for a Planted Tank', slug: 'choosing-right-light-planted-tank',
    description: 'How to match your lighting to your plants without fueling an algae bloom.',
    content: 'Low-light plants like Java Fern and Anubias thrive under modest LED output, while stem plants and carpeting species need stronger, full-spectrum fixtures. Start with 6-8 hours of light per day and adjust based on algae growth rather than guessing at wattage alone.',
    image: 'https://images.unsplash.com/photo-1544923246-77307dd654cb?w=1200&q=80',
    category: 'Plants', author: 'Priya Nair', publishedDate: '2026-02-09', status: 'Published',
    tags: ['lighting', 'plants'],
  },
  {
    id: 'blog-7', title: 'Betta Fish Care 101', slug: 'betta-fish-care-101',
    description: 'What every new Betta owner should know about tank size, temperature, and tankmates.',
    content: 'Despite their reputation as "low-maintenance," Bettas do best in heated, filtered tanks of at least 5 gallons — not bowls. They are generally solitary and should not be housed with fin-nipping species or other Bettas.',
    image: 'https://images.unsplash.com/photo-1520302659201-63bdcc245f4d?w=1200&q=80',
    category: 'Fish Care', author: 'Maya Chen', publishedDate: '2026-02-16', status: 'Published',
    tags: ['betta', 'care-guide'],
  },
  {
    id: 'blog-8', title: 'Signs of a Healthy vs. Stressed Fish', slug: 'signs-healthy-vs-stressed-fish',
    description: 'Learn to read body language, color, and behavior before problems become serious.',
    content: 'Healthy fish display steady color, active swimming, and normal appetite. Watch for clamped fins, rapid gilling, hiding, or color loss, which often signal poor water quality or early illness — testing water parameters is usually the first diagnostic step.',
    image: 'https://images.unsplash.com/photo-1522911512095-8ce38fbc37e6?w=1200&q=80',
    category: 'Fish Care', author: 'Dr. Owen Reyes', publishedDate: '2026-02-23', status: 'Published',
    tags: ['health', 'observation'],
  },
  {
    id: 'blog-9', title: 'Freshwater vs. Saltwater: Which Is Right for You?', slug: 'freshwater-vs-saltwater-which-right-for-you',
    description: 'Comparing cost, maintenance, and difficulty before choosing your first tank type.',
    content: 'Freshwater tanks are generally more forgiving and less expensive to start, making them the recommended path for beginners. Saltwater and reef tanks offer stunning color and biodiversity but demand tighter water parameter control and specialized equipment.',
    image: 'https://images.unsplash.com/photo-1499242611767-cf8b9be02854?w=1200&q=80',
    category: 'Getting Started', author: 'Priya Nair', publishedDate: '2026-03-02', status: 'Published',
    tags: ['freshwater', 'saltwater'],
  },
  {
    id: 'blog-10', title: 'Aquascaping Basics: Building Your First Layout', slug: 'aquascaping-basics-first-layout',
    description: 'Simple design principles for a natural-looking tank using rocks, wood, and plants.',
    content: 'Odd-numbered groupings of hardscape, a clear focal point, and varying plant heights front-to-back create depth in even a small tank. Start with two or three types of plants and one hardscape material before adding complexity.',
    image: 'https://images.unsplash.com/photo-1520301255226-bf5f144451c1?w=1200&q=80',
    category: 'Plants', author: 'Maya Chen', publishedDate: '2026-03-09', status: 'Published',
    tags: ['aquascaping', 'design'],
  },
  {
    id: 'blog-11', title: 'Quarantining New Fish the Right Way', slug: 'quarantining-new-fish-right-way',
    description: 'Why a quarantine tank protects your whole collection from disease outbreaks.',
    content: 'A simple 10-20 gallon quarantine tank with a sponge filter and heater lets you observe new arrivals for 2-4 weeks before introducing them to your main display, catching parasites or disease before they spread.',
    image: 'https://images.unsplash.com/photo-1571752726703-5e7d1f6a986d?w=1200&q=80',
    category: 'Fish Care', author: 'Dr. Owen Reyes', publishedDate: '2026-03-16', status: 'Published',
    tags: ['quarantine', 'disease-prevention'],
  },
];
