import { Category } from '../models';

export const MOCK_CATEGORIES: Category[] = [
  {
    id: 'cat-fish',
    name: 'Fish',
    slug: 'fish',
    description: 'Freshwater and tropical fish for every skill level, from hardy beginner species to vibrant showpiece breeds.',
    image: 'https://images.unsplash.com/photo-1524704796725-9fc3044a58b2?w=800&q=80',
    displayOrder: 1,
    isFeatured: true,
    isActive: true,
  },
  {
    id: 'cat-fish-food',
    name: 'Fish Food',
    slug: 'fish-food',
    description: 'Flakes, pellets, and live feed formulated for healthy color, growth, and digestion.',
    image: 'https://images.unsplash.com/photo-1596797882870-8c33deeaaa8e?w=800&q=80',
    displayOrder: 2,
    isFeatured: true,
    isActive: true,
  },
  {
    id: 'cat-accessories',
    name: 'Accessories',
    slug: 'accessories',
    description: 'Everything else your aquarium needs — tanks, filtration, lighting, plants, and care essentials.',
    image: 'https://images.unsplash.com/photo-1520302519104-c452c2eddb56?w=800&q=80',
    displayOrder: 3,
    isFeatured: true,
    isActive: true,
  },
  {
    id: 'cat-tanks',
    name: 'Aquarium Tanks',
    slug: 'aquarium-tanks',
    description: 'Glass and acrylic tanks and starter kits in every size, from nano desktop tanks to full room centerpieces.',
    image: 'https://images.unsplash.com/photo-1522069169874-c58ec4b76be5?w=800&q=80',
    parentId: 'cat-accessories',
    displayOrder: 1,
    isFeatured: true,
    isActive: true,
  },
  {
    id: 'cat-plants',
    name: 'Aquarium Plants',
    slug: 'aquarium-plants',
    description: 'Live and hardy aquatic plants that oxygenate water and give fish natural cover.',
    image: 'https://images.unsplash.com/photo-1524683079666-091ec38e2c78?w=800&q=80',
    parentId: 'cat-accessories',
    displayOrder: 2,
    isFeatured: true,
    isActive: true,
  },
  {
    id: 'cat-filters',
    name: 'Filters',
    slug: 'filters',
    description: 'Canister, hang-on-back, and sponge filters for crystal-clear, healthy water.',
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80',
    parentId: 'cat-accessories',
    displayOrder: 3,
    isFeatured: false,
    isActive: true,
  },
  {
    id: 'cat-air-pumps',
    name: 'Air Pumps',
    slug: 'air-pumps',
    description: 'Quiet, energy-efficient air pumps for reliable oxygenation.',
    image: 'https://images.unsplash.com/photo-1520302659201-63bdcc245f4d?w=800&q=80',
    parentId: 'cat-accessories',
    displayOrder: 4,
    isFeatured: false,
    isActive: true,
  },
  {
    id: 'cat-water-pumps',
    name: 'Water Pumps',
    slug: 'water-pumps',
    description: 'Circulation and wavemaker pumps for stronger flow and healthier tanks.',
    image: 'https://images.unsplash.com/photo-1499242611767-cf8b9be02854?w=800&q=80',
    parentId: 'cat-accessories',
    displayOrder: 5,
    isFeatured: false,
    isActive: true,
  },
  {
    id: 'cat-heaters',
    name: 'Heaters',
    slug: 'heaters',
    description: 'Precision aquarium heaters that hold stable, tropical-safe temperatures.',
    image: 'https://images.unsplash.com/photo-1571752726703-5e7d1f6a986d?w=800&q=80',
    parentId: 'cat-accessories',
    displayOrder: 6,
    isFeatured: false,
    isActive: true,
  },
  {
    id: 'cat-lighting',
    name: 'Lighting',
    slug: 'lighting',
    description: 'Full-spectrum LED lighting that supports plant growth and shows off natural fish color.',
    image: 'https://images.unsplash.com/photo-1544923246-77307dd654cb?w=800&q=80',
    parentId: 'cat-accessories',
    displayOrder: 7,
    isFeatured: true,
    isActive: true,
  },
  {
    id: 'cat-decorations',
    name: 'Decorations',
    slug: 'decorations',
    description: 'Driftwood, rockwork, and ornaments that create natural hiding spots and striking aquascapes.',
    image: 'https://images.unsplash.com/photo-1520301255226-bf5f144451c1?w=800&q=80',
    parentId: 'cat-accessories',
    displayOrder: 8,
    isFeatured: false,
    isActive: true,
  },
  {
    id: 'cat-cleaning',
    name: 'Cleaning Equipment',
    slug: 'cleaning-equipment',
    description: 'Gravel vacuums, algae scrapers, and water conditioners that make maintenance simple.',
    image: 'https://images.unsplash.com/photo-1584967911318-3ce0dd6f4ca0?w=800&q=80',
    parentId: 'cat-accessories',
    displayOrder: 9,
    isFeatured: false,
    isActive: true,
  },
  {
    id: 'cat-fish-care',
    name: 'Fish Care',
    slug: 'fish-care',
    description: 'Medicines, water conditioners, and test kits to keep fish healthy and water balanced.',
    image: 'https://images.unsplash.com/photo-1522911512095-8ce38fbc37e6?w=800&q=80',
    parentId: 'cat-accessories',
    displayOrder: 10,
    isFeatured: false,
    isActive: true,
  },
];
