import { Product } from '../models';

/**
 * Realistic aquarium catalog. Fish and Fish Food are primary categories;
 * everything else lives under Accessories via subcategoryId.
 */
export const MOCK_PRODUCTS: Product[] = [
  // ───────────────────────── FISH ─────────────────────────
  {
    id: 'p-neon-tetra', sku: 'FSH-001', slug: 'neon-tetra', name: 'Neon Tetra',
    categoryId: 'cat-fish', brand: 'AquaLife',
    shortDescription: 'A schooling classic with an electric blue-and-red stripe.',
    description: 'Neon Tetras are peaceful, hardy schoolers that bring vivid color to any community tank. Best kept in groups of 6 or more, they thrive in softly lit, planted aquariums with stable water conditions.',
    images: ['https://images.unsplash.com/photo-1520302519104-c452c2eddb56?w=900&q=80'],
    price: 4.49, salePrice: undefined, currency: 'NPR',
    stockQuantity: 86, minimumStock: 15, trackInventory: true, allowBackorders: false,
    rating: { average: 4.8, count: 212 },
    attributes: [
      { label: 'Fish Type', value: 'Tetra' }, { label: 'Size', value: '1.5 in' },
      { label: 'Color', value: 'Blue & Red' }, { label: 'Water Temperature', value: '72–78°F' },
      { label: 'pH', value: '6.0–7.0' }, { label: 'Compatibility', value: 'Peaceful community' },
      { label: 'Care Level', value: 'Easy' }, { label: 'Expected Lifespan', value: '5–8 years' },
    ],
    specifications: [{ label: 'Minimum Tank Size', value: '10 gal' }, { label: 'Diet', value: 'Omnivore' }],
    tags: ['schooling', 'beginner-friendly', 'community'], badges: ['BEST SELLER'],
    isActive: true, isFeatured: true, createdAt: '2025-11-02',
    seo: { metaTitle: 'Neon Tetra — Live Freshwater Fish | AquaShop', metaDescription: 'Buy healthy Neon Tetras online. Hardy, colorful schooling fish perfect for community tanks.' },
  },
  {
    id: 'p-betta-fish', sku: 'FSH-002', slug: 'betta-fish', name: 'Betta Fish',
    categoryId: 'cat-fish', brand: 'AquaLife',
    shortDescription: 'Flowing fins and jewel-toned color in a low-maintenance solo fish.',
    description: 'Also known as the Siamese Fighting Fish, the Betta is prized for its flowing fins and rich color variety. Bettas do best alone or with carefully chosen tankmates, in a heated, filtered tank.',
    images: ['https://images.unsplash.com/photo-1524704796725-9fc3044a58b2?w=900&q=80'],
    price: 12.99, currency: 'NPR',
    stockQuantity: 40, minimumStock: 10, trackInventory: true, allowBackorders: false,
    rating: { average: 4.9, count: 341 },
    attributes: [
      { label: 'Fish Type', value: 'Betta' }, { label: 'Size', value: '2.5 in' },
      { label: 'Color', value: 'Assorted' }, { label: 'Water Temperature', value: '76–82°F' },
      { label: 'pH', value: '6.5–7.5' }, { label: 'Compatibility', value: 'Solo or peaceful tankmates only' },
      { label: 'Care Level', value: 'Easy' }, { label: 'Expected Lifespan', value: '3–5 years' },
    ],
    specifications: [{ label: 'Minimum Tank Size', value: '5 gal' }, { label: 'Diet', value: 'Carnivore' }],
    tags: ['centerpiece', 'solo', 'colorful'], badges: ['BEST SELLER', 'NEW'],
    isActive: true, isFeatured: true, createdAt: '2026-01-15',
    seo: { metaTitle: 'Betta Fish — Live Siamese Fighting Fish | AquaShop', metaDescription: 'Shop vibrant, healthy Betta fish with flowing fins, ready to ship.' },
  },
  {
    id: 'p-fancy-goldfish', sku: 'FSH-003', slug: 'fancy-goldfish', name: 'Fancy Goldfish',
    categoryId: 'cat-fish', brand: 'PondCraft',
    shortDescription: 'Rounded body and flowing double tail in classic orange-and-white.',
    description: 'Fancy Goldfish are hardy, personable fish suited to spacious tanks or ponds. They love room to swim and benefit from strong filtration due to their appetite.',
    images: ['https://images.unsplash.com/photo-1522069169874-c58ec4b76be5?w=900&q=80'],
    price: 9.99, currency: 'NPR',
    stockQuantity: 30, minimumStock: 8, trackInventory: true, allowBackorders: false,
    rating: { average: 4.6, count: 98 },
    attributes: [
      { label: 'Fish Type', value: 'Goldfish' }, { label: 'Size', value: '3 in' },
      { label: 'Color', value: 'Orange & White' }, { label: 'Water Temperature', value: '65–72°F' },
      { label: 'pH', value: '7.0–8.0' }, { label: 'Compatibility', value: 'Other goldfish' },
      { label: 'Care Level', value: 'Moderate' }, { label: 'Expected Lifespan', value: '10–15 years' },
    ],
    specifications: [{ label: 'Minimum Tank Size', value: '20 gal' }, { label: 'Diet', value: 'Omnivore' }],
    tags: ['cold-water', 'pond-safe'], badges: [],
    isActive: true, isFeatured: false, createdAt: '2025-09-20',
    seo: { metaTitle: 'Fancy Goldfish — Live Fish | AquaShop', metaDescription: 'Hardy, colorful Fancy Goldfish for tanks and ponds.' },
  },
  {
    id: 'p-guppy', sku: 'FSH-004', slug: 'guppy', name: 'Guppy',
    categoryId: 'cat-fish', brand: 'AquaLife',
    shortDescription: 'Prolific, colorful, and endlessly easy to keep.',
    description: 'Guppies are among the easiest fish to keep, tolerating a wide range of water conditions while showing off tail patterns in nearly every color.',
    images: ['https://images.unsplash.com/photo-1520302659201-63bdcc245f4d?w=900&q=80'],
    price: 3.99, currency: 'NPR',
    stockQuantity: 120, minimumStock: 20, trackInventory: true, allowBackorders: false,
    rating: { average: 4.7, count: 156 },
    attributes: [
      { label: 'Fish Type', value: 'Guppy' }, { label: 'Size', value: '1.5 in' },
      { label: 'Color', value: 'Assorted' }, { label: 'Water Temperature', value: '72–79°F' },
      { label: 'pH', value: '7.0–8.0' }, { label: 'Compatibility', value: 'Peaceful community' },
      { label: 'Care Level', value: 'Easy' }, { label: 'Expected Lifespan', value: '2–3 years' },
    ],
    specifications: [{ label: 'Minimum Tank Size', value: '10 gal' }, { label: 'Diet', value: 'Omnivore' }],
    tags: ['beginner-friendly', 'schooling'], badges: ['NEW'],
    isActive: true, isFeatured: false, createdAt: '2026-02-01',
    seo: { metaTitle: 'Guppy Fish — Live Freshwater Fish | AquaShop', metaDescription: 'Colorful, hardy Guppies for beginner and community tanks.' },
  },
  {
    id: 'p-angelfish', sku: 'FSH-005', slug: 'angelfish', name: 'Angelfish',
    categoryId: 'cat-fish', brand: 'AquaLife',
    shortDescription: 'A graceful, tall-bodied centerpiece for larger community tanks.',
    description: 'Angelfish bring elegant vertical silhouettes and calm movement to taller aquariums. They pair well with similarly sized, peaceful tankmates.',
    images: ['https://images.unsplash.com/photo-1499242611767-cf8b9be02854?w=900&q=80'],
    price: 14.49, currency: 'NPR',
    stockQuantity: 22, minimumStock: 6, trackInventory: true, allowBackorders: false,
    rating: { average: 4.7, count: 74 },
    attributes: [
      { label: 'Fish Type', value: 'Cichlid' }, { label: 'Size', value: '3 in' },
      { label: 'Color', value: 'Silver & Black' }, { label: 'Water Temperature', value: '76–84°F' },
      { label: 'pH', value: '6.5–7.5' }, { label: 'Compatibility', value: 'Medium community, avoid small fish' },
      { label: 'Care Level', value: 'Moderate' }, { label: 'Expected Lifespan', value: '10 years' },
    ],
    specifications: [{ label: 'Minimum Tank Size', value: '29 gal' }, { label: 'Diet', value: 'Omnivore' }],
    tags: ['centerpiece', 'tall-tank'], badges: [],
    isActive: true, isFeatured: true, createdAt: '2025-10-11',
    seo: { metaTitle: 'Angelfish — Live Freshwater Cichlid | AquaShop', metaDescription: 'Elegant Angelfish for medium to large community aquariums.' },
  },
  {
    id: 'p-cory-catfish', sku: 'FSH-006', slug: 'cory-catfish', name: 'Cory Catfish',
    categoryId: 'cat-fish', brand: 'AquaLife',
    shortDescription: 'A friendly bottom-dweller that keeps the substrate clean.',
    description: 'Corydoras catfish are gentle, social bottom-feeders that patrol the substrate for leftover food, best kept in groups of 4 or more.',
    images: ['https://images.unsplash.com/photo-1571752726703-5e7d1f6a986d?w=900&q=80'],
    price: 5.99, currency: 'NPR',
    stockQuantity: 54, minimumStock: 10, trackInventory: true, allowBackorders: false,
    rating: { average: 4.8, count: 61 },
    attributes: [
      { label: 'Fish Type', value: 'Catfish' }, { label: 'Size', value: '2 in' },
      { label: 'Color', value: 'Bronze' }, { label: 'Water Temperature', value: '72–78°F' },
      { label: 'pH', value: '6.5–7.5' }, { label: 'Compatibility', value: 'Peaceful community' },
      { label: 'Care Level', value: 'Easy' }, { label: 'Expected Lifespan', value: '5 years' },
    ],
    specifications: [{ label: 'Minimum Tank Size', value: '10 gal' }, { label: 'Diet', value: 'Omnivore' }],
    tags: ['bottom-dweller', 'cleanup-crew'], badges: [],
    isActive: true, isFeatured: false, createdAt: '2025-08-19',
    seo: { metaTitle: 'Cory Catfish — Live Bottom-Feeder Fish | AquaShop', metaDescription: 'Peaceful Cory Catfish, great for substrate cleanup in community tanks.' },
  },

  // ───────────────────────── FISH FOOD ─────────────────────────
  {
    id: 'p-tropical-flakes', sku: 'FD-001', slug: 'tropical-fish-flakes', name: 'Tropical Fish Flakes',
    categoryId: 'cat-fish-food', brand: 'ReefNutri',
    shortDescription: 'Daily staple flake food for vibrant color and steady growth.',
    description: 'A balanced flake formula with natural color enhancers and essential vitamins, floats initially then slowly sinks to reach mid-water feeders.',
    images: ['https://images.unsplash.com/photo-1596797882870-8c33deeaaa8e?w=900&q=80'],
    price: 8.99, currency: 'NPR',
    stockQuantity: 74, minimumStock: 15, trackInventory: true, allowBackorders: true,
    rating: { average: 4.6, count: 189 },
    attributes: [
      { label: 'Food Type', value: 'Flake' }, { label: 'Weight', value: '7.06 oz' },
      { label: 'Fish Type', value: 'Tropical Freshwater' }, { label: 'Age Group', value: 'All Life Stages' },
      { label: 'Ingredients', value: 'Fish meal, wheat flour, spirulina, vitamins' },
    ],
    specifications: [{ label: 'Feeding Frequency', value: '1–2x daily' }],
    tags: ['staple-food', 'daily-feed'], badges: ['BEST SELLER'],
    isActive: true, isFeatured: true, createdAt: '2025-07-04',
    seo: { metaTitle: 'Tropical Fish Flakes | AquaShop', metaDescription: 'Balanced daily flake food for vivid color and healthy growth.' },
  },
  {
    id: 'p-betta-pellets', sku: 'FD-002', slug: 'betta-pellets', name: 'Betta Pellets',
    categoryId: 'cat-fish-food', brand: 'ReefNutri',
    shortDescription: 'Protein-rich floating pellets sized for Betta mouths.',
    description: 'Slow-sinking pellets formulated with high protein content to support the natural carnivorous diet of Bettas and reduce waste.',
    images: ['https://images.unsplash.com/photo-1584967911318-3ce0dd6f4ca0?w=900&q=80'],
    price: 6.49, currency: 'NPR',
    stockQuantity: 60, minimumStock: 15, trackInventory: true, allowBackorders: true,
    rating: { average: 4.7, count: 143 },
    attributes: [
      { label: 'Food Type', value: 'Pellet' }, { label: 'Weight', value: '1.2 oz' },
      { label: 'Fish Type', value: 'Betta' }, { label: 'Age Group', value: 'Adult' },
      { label: 'Ingredients', value: 'Fish meal, shrimp meal, vitamins' },
    ],
    specifications: [{ label: 'Feeding Frequency', value: '2x daily' }],
    tags: ['betta', 'protein-rich'], badges: [],
    isActive: true, isFeatured: false, createdAt: '2025-12-05',
    seo: { metaTitle: 'Betta Pellets | AquaShop', metaDescription: 'High-protein floating pellets formulated for Betta fish.' },
  },
  {
    id: 'p-goldfish-food', sku: 'FD-003', slug: 'goldfish-food', name: 'Goldfish Food',
    categoryId: 'cat-fish-food', brand: 'PondCraft',
    shortDescription: 'Easy-to-digest floating sticks for goldfish and koi.',
    description: 'Wheat-germ based sticks that are gentle on sensitive goldfish digestion, supporting healthy growth without clouding water.',
    images: ['https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=900&q=80'],
    price: 5.49, currency: 'NPR',
    stockQuantity: 5, minimumStock: 10, trackInventory: true, allowBackorders: true,
    rating: { average: 4.4, count: 87 },
    attributes: [
      { label: 'Food Type', value: 'Floating Stick' }, { label: 'Weight', value: '10 oz' },
      { label: 'Fish Type', value: 'Goldfish/Koi' }, { label: 'Age Group', value: 'All Life Stages' },
      { label: 'Ingredients', value: 'Wheat germ, fish meal, algae' },
    ],
    specifications: [{ label: 'Feeding Frequency', value: '1–2x daily' }],
    tags: ['goldfish', 'pond-safe'], badges: ['LOW STOCK'],
    isActive: true, isFeatured: false, createdAt: '2025-06-14',
    seo: { metaTitle: 'Goldfish Food | AquaShop', metaDescription: 'Wheat-germ based floating sticks for goldfish and koi.' },
  },
  {
    id: 'p-freeze-dried-brine', sku: 'FD-004', slug: 'freeze-dried-brine-shrimp', name: 'Freeze-Dried Brine Shrimp',
    categoryId: 'cat-fish-food', brand: 'ReefNutri',
    shortDescription: 'A protein-packed treat that fish go wild for.',
    description: 'Whole brine shrimp, freeze-dried to lock in nutrients, ideal as a supplemental treat to encourage natural foraging behavior.',
    images: ['https://images.unsplash.com/photo-1522911512095-8ce38fbc37e6?w=900&q=80'],
    price: 7.99, currency: 'NPR',
    stockQuantity: 45, minimumStock: 10, trackInventory: true, allowBackorders: true,
    rating: { average: 4.8, count: 121 },
    attributes: [
      { label: 'Food Type', value: 'Freeze-Dried' }, { label: 'Weight', value: '0.5 oz' },
      { label: 'Fish Type', value: 'Most Freshwater & Marine' }, { label: 'Age Group', value: 'Juvenile & Adult' },
      { label: 'Ingredients', value: '100% brine shrimp' },
    ],
    specifications: [{ label: 'Feeding Frequency', value: '2–3x weekly (treat)' }],
    tags: ['treat', 'high-protein'], badges: ['NEW'],
    isActive: true, isFeatured: true, createdAt: '2026-01-28',
    seo: { metaTitle: 'Freeze-Dried Brine Shrimp | AquaShop', metaDescription: 'Nutrient-rich freeze-dried brine shrimp treat for freshwater and marine fish.' },
  },

  // ───────────────────────── AQUARIUM TANKS ─────────────────────────
  {
    id: 'p-starter-kit-20', sku: 'TK-001', slug: 'aquarium-starter-kit-20gal', name: 'Aquarium Starter Kit (20 Gal)',
    categoryId: 'cat-accessories', subcategoryId: 'cat-tanks', brand: 'ReefTech',
    shortDescription: 'Everything a beginner needs: tank, filter, light, and lid in one box.',
    description: 'This all-in-one 20-gallon kit includes a rimless glass tank, quiet hang-on filter, full-spectrum LED hood, and a starter water conditioner sample — ideal for a first freshwater setup.',
    images: ['https://images.unsplash.com/photo-1522069169874-c58ec4b76be5?w=900&q=80'],
    price: 129.99, salePrice: 104.99, currency: 'NPR',
    stockQuantity: 18, minimumStock: 5, trackInventory: true, allowBackorders: false,
    rating: { average: 4.7, count: 96 },
    attributes: [
      { label: 'Capacity', value: '20 gal' }, { label: 'Dimensions', value: '24 x 12 x 16 in' },
      { label: 'Material', value: 'Glass' }, { label: 'Brand', value: 'ReefTech' }, { label: 'Power', value: '15W LED' },
    ],
    specifications: [{ label: 'Includes', value: 'Tank, filter, LED hood, conditioner sample' }],
    tags: ['starter-kit', 'beginner-friendly'], badges: ['SALE', 'BEST SELLER'],
    isActive: true, isFeatured: true, createdAt: '2025-09-01',
    seo: { metaTitle: 'Aquarium Starter Kit 20 Gallon | AquaShop', metaDescription: 'Complete 20-gallon starter kit with tank, filter, and LED lighting.' },
  },
  {
    id: 'p-nano-tank-5', sku: 'TK-002', slug: 'nano-desktop-tank-5gal', name: 'Nano Desktop Tank (5 Gal)',
    categoryId: 'cat-accessories', subcategoryId: 'cat-tanks', brand: 'ReefTech',
    shortDescription: 'A compact, low-iron glass tank made for desks and shelves.',
    description: 'Low-iron glass gives this nano tank exceptional clarity, ideal for a Betta, nano shrimp, or a small planted aquascape.',
    images: ['https://images.unsplash.com/photo-1520302519104-c452c2eddb56?w=900&q=80'],
    price: 49.99, currency: 'NPR',
    stockQuantity: 32, minimumStock: 8, trackInventory: true, allowBackorders: false,
    rating: { average: 4.5, count: 58 },
    attributes: [
      { label: 'Capacity', value: '5 gal' }, { label: 'Dimensions', value: '14 x 8 x 10 in' },
      { label: 'Material', value: 'Low-Iron Glass' }, { label: 'Brand', value: 'ReefTech' },
    ],
    specifications: [{ label: 'Includes', value: 'Tank only' }],
    tags: ['nano', 'desktop'], badges: [],
    isActive: true, isFeatured: false, createdAt: '2025-11-22',
    seo: { metaTitle: 'Nano Desktop Tank 5 Gallon | AquaShop', metaDescription: 'Crystal-clear low-iron glass nano tank for desktop aquascapes.' },
  },
  {
    id: 'p-reef-tank-55', sku: 'TK-003', slug: 'aquarium-tank-55gal', name: 'Aquarium Tank (55 Gal)',
    categoryId: 'cat-accessories', subcategoryId: 'cat-tanks', brand: 'ReefTech',
    shortDescription: 'A spacious statement tank built for community and cichlid setups.',
    description: 'Braced glass construction gives this 55-gallon tank the strength for a larger aquascape, tall enough for angelfish and roomy enough for an active community.',
    images: ['https://images.unsplash.com/photo-1522069169874-c58ec4b76be5?w=900&q=80'],
    price: 219.99, currency: 'NPR',
    stockQuantity: 9, minimumStock: 3, trackInventory: true, allowBackorders: false,
    rating: { average: 4.6, count: 34 },
    attributes: [
      { label: 'Capacity', value: '55 gal' }, { label: 'Dimensions', value: '48 x 13 x 21 in' },
      { label: 'Material', value: 'Glass' }, { label: 'Brand', value: 'ReefTech' },
    ],
    specifications: [{ label: 'Includes', value: 'Tank only' }],
    tags: ['large-tank', 'community'], badges: [],
    isActive: true, isFeatured: false, createdAt: '2025-05-30',
    seo: { metaTitle: 'Aquarium Tank 55 Gallon | AquaShop', metaDescription: 'Spacious 55-gallon glass tank for community and cichlid aquariums.' },
  },

  // ───────────────────────── PLANTS ─────────────────────────
  {
    id: 'p-java-fern', sku: 'PL-001', slug: 'java-fern', name: 'Java Fern',
    categoryId: 'cat-accessories', subcategoryId: 'cat-plants', brand: 'GreenReef',
    shortDescription: 'An unkillable, low-light plant that attaches to wood and rock.',
    description: 'Java Fern thrives in low to moderate light and doesn\u2019t need substrate — simply tie it to driftwood or rock and let the roots take hold.',
    images: ['https://images.unsplash.com/photo-1524683079666-091ec38e2c78?w=900&q=80'],
    price: 6.99, currency: 'NPR',
    stockQuantity: 65, minimumStock: 15, trackInventory: true, allowBackorders: true,
    rating: { average: 4.9, count: 178 },
    attributes: [
      { label: 'Light Requirement', value: 'Low–Medium' }, { label: 'Placement', value: 'Attach to hardscape' },
      { label: 'Growth Rate', value: 'Slow' }, { label: 'Care Level', value: 'Easy' },
    ],
    specifications: [{ label: 'CO2 Required', value: 'No' }],
    tags: ['low-light', 'beginner-plant'], badges: ['BEST SELLER'],
    isActive: true, isFeatured: true, createdAt: '2025-08-08',
    seo: { metaTitle: 'Java Fern — Live Aquarium Plant | AquaShop', metaDescription: 'Hardy, low-light Java Fern, easy to attach to driftwood or rock.' },
  },
  {
    id: 'p-anubias', sku: 'PL-002', slug: 'anubias-plant', name: 'Anubias Plant',
    categoryId: 'cat-accessories', subcategoryId: 'cat-plants', brand: 'GreenReef',
    shortDescription: 'Broad, sturdy leaves that stand up to grazing fish.',
    description: 'Anubias is nearly indestructible, tolerating low light and a wide range of water conditions while providing sturdy cover for shy fish.',
    images: ['https://images.unsplash.com/photo-1524683079666-091ec38e2c78?w=900&q=80'],
    price: 8.49, currency: 'NPR',
    stockQuantity: 50, minimumStock: 12, trackInventory: true, allowBackorders: true,
    rating: { average: 4.8, count: 132 },
    attributes: [
      { label: 'Light Requirement', value: 'Low' }, { label: 'Placement', value: 'Attach to hardscape' },
      { label: 'Growth Rate', value: 'Very Slow' }, { label: 'Care Level', value: 'Easy' },
    ],
    specifications: [{ label: 'CO2 Required', value: 'No' }],
    tags: ['low-light', 'hardy'], badges: [],
    isActive: true, isFeatured: false, createdAt: '2025-10-02',
    seo: { metaTitle: 'Anubias — Live Aquarium Plant | AquaShop', metaDescription: 'Sturdy, low-maintenance Anubias plant for any freshwater tank.' },
  },
  {
    id: 'p-amazon-sword', sku: 'PL-003', slug: 'amazon-sword-plant', name: 'Amazon Sword Plant',
    categoryId: 'cat-accessories', subcategoryId: 'cat-plants', brand: 'GreenReef',
    shortDescription: 'A bold, tall centerpiece plant for the background of the tank.',
    description: 'Broad sword-shaped leaves make this a striking background plant, rooting in substrate and growing tall with good lighting.',
    images: ['https://images.unsplash.com/photo-1524683079666-091ec38e2c78?w=900&q=80'],
    price: 9.99, currency: 'NPR',
    stockQuantity: 38, minimumStock: 10, trackInventory: true, allowBackorders: true,
    rating: { average: 4.6, count: 71 },
    attributes: [
      { label: 'Light Requirement', value: 'Medium–High' }, { label: 'Placement', value: 'Substrate/Background' },
      { label: 'Growth Rate', value: 'Moderate' }, { label: 'Care Level', value: 'Easy' },
    ],
    specifications: [{ label: 'CO2 Required', value: 'Beneficial, not required' }],
    tags: ['background-plant', 'centerpiece'], badges: [],
    isActive: true, isFeatured: false, createdAt: '2025-07-19',
    seo: { metaTitle: 'Amazon Sword Plant | AquaShop', metaDescription: 'Bold background sword plant for freshwater aquariums.' },
  },

  // ───────────────────────── FILTERS ─────────────────────────
  {
    id: 'p-canister-filter', sku: 'FL-001', slug: 'external-canister-filter', name: 'External Canister Filter',
    categoryId: 'cat-accessories', subcategoryId: 'cat-filters', brand: 'ReefTech',
    shortDescription: 'Multi-stage filtration for tanks up to 75 gallons.',
    description: 'This external canister filter runs mechanical, biological, and chemical media stages for powerful, quiet filtration well suited to medium and large aquariums.',
    images: ['https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=900&q=80'],
    price: 89.99, currency: 'NPR',
    stockQuantity: 0, minimumStock: 5, trackInventory: true, allowBackorders: true,
    rating: { average: 4.7, count: 104 },
    attributes: [
      { label: 'Capacity', value: 'Up to 75 gal' }, { label: 'Flow Rate', value: '265 GPH' },
      { label: 'Material', value: 'ABS Plastic' }, { label: 'Brand', value: 'ReefTech' }, { label: 'Power', value: '18W' },
    ],
    specifications: [{ label: 'Media Included', value: 'Foam, ceramic rings, activated carbon' }],
    tags: ['filtration', 'canister'], badges: [],
    isActive: true, isFeatured: true, createdAt: '2025-09-14',
    seo: { metaTitle: 'External Canister Filter | AquaShop', metaDescription: 'Powerful multi-stage canister filter for medium to large aquariums.' },
  },
  {
    id: 'p-hob-filter', sku: 'FL-002', slug: 'hang-on-back-filter', name: 'Hang-On-Back Filter',
    categoryId: 'cat-accessories', subcategoryId: 'cat-filters', brand: 'ReefTech',
    shortDescription: 'A quiet, easy-to-service filter for tanks up to 30 gallons.',
    description: 'Simple to install on the back of the tank, with replaceable cartridges for mechanical and chemical filtration and an adjustable flow rate.',
    images: ['https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=900&q=80'],
    price: 34.99, currency: 'NPR',
    stockQuantity: 41, minimumStock: 10, trackInventory: true, allowBackorders: false,
    rating: { average: 4.5, count: 87 },
    attributes: [
      { label: 'Capacity', value: 'Up to 30 gal' }, { label: 'Flow Rate', value: '150 GPH' },
      { label: 'Material', value: 'Plastic' }, { label: 'Brand', value: 'ReefTech' }, { label: 'Power', value: '7W' },
    ],
    specifications: [{ label: 'Media Included', value: 'Replaceable cartridge' }],
    tags: ['filtration', 'beginner-friendly'], badges: [],
    isActive: true, isFeatured: false, createdAt: '2025-06-27',
    seo: { metaTitle: 'Hang-On-Back Filter | AquaShop', metaDescription: 'Easy-to-install hang-on-back filter for small to medium tanks.' },
  },
  {
    id: 'p-sponge-filter', sku: 'FL-003', slug: 'sponge-filter', name: 'Sponge Filter',
    categoryId: 'cat-accessories', subcategoryId: 'cat-filters', brand: 'AquaLife',
    shortDescription: 'Gentle biological filtration, safe for fry and shrimp.',
    description: 'Powered by an air pump, this sponge filter offers gentle flow and excellent biological filtration without pulling in fry or shrimp.',
    images: ['https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=900&q=80'],
    price: 12.99, currency: 'NPR',
    stockQuantity: 55, minimumStock: 12, trackInventory: true, allowBackorders: true,
    rating: { average: 4.6, count: 63 },
    attributes: [
      { label: 'Capacity', value: 'Up to 20 gal' }, { label: 'Flow Rate', value: 'Air-driven' },
      { label: 'Material', value: 'Foam' }, { label: 'Brand', value: 'AquaLife' },
    ],
    specifications: [{ label: 'Requires', value: 'Air pump (sold separately)' }],
    tags: ['fry-safe', 'shrimp-safe'], badges: [],
    isActive: true, isFeatured: false, createdAt: '2025-12-18',
    seo: { metaTitle: 'Sponge Filter | AquaShop', metaDescription: 'Gentle, fry-safe sponge filter for breeding and shrimp tanks.' },
  },

  // ───────────────────────── AIR PUMPS ─────────────────────────
  {
    id: 'p-air-pump', sku: 'AP-001', slug: 'quiet-air-pump', name: 'Quiet Air Pump',
    categoryId: 'cat-accessories', subcategoryId: 'cat-air-pumps', brand: 'ReefTech',
    shortDescription: 'Whisper-quiet oxygenation for tanks up to 40 gallons.',
    description: 'A dual-outlet air pump with a noise-dampening design, ideal for powering sponge filters, air stones, and ornaments.',
    images: ['https://images.unsplash.com/photo-1520302659201-63bdcc245f4d?w=900&q=80'],
    price: 19.99, currency: 'NPR',
    stockQuantity: 47, minimumStock: 10, trackInventory: true, allowBackorders: false,
    rating: { average: 4.5, count: 92 },
    attributes: [
      { label: 'Capacity', value: 'Up to 40 gal' }, { label: 'Outlets', value: '2' },
      { label: 'Material', value: 'Plastic' }, { label: 'Brand', value: 'ReefTech' }, { label: 'Power', value: '3W' },
    ],
    specifications: [{ label: 'Noise Level', value: 'Under 30 dB' }],
    tags: ['quiet', 'oxygenation'], badges: [],
    isActive: true, isFeatured: false, createdAt: '2025-11-09',
    seo: { metaTitle: 'Quiet Air Pump | AquaShop', metaDescription: 'Whisper-quiet dual-outlet air pump for reliable oxygenation.' },
  },

  // ───────────────────────── WATER PUMPS ─────────────────────────
  {
    id: 'p-water-pump', sku: 'WP-001', slug: 'submersible-water-pump', name: 'Submersible Water Pump',
    categoryId: 'cat-accessories', subcategoryId: 'cat-water-pumps', brand: 'ReefTech',
    shortDescription: 'Compact circulation pump for water changes and wave flow.',
    description: 'A versatile submersible pump for drainage during water changes, waterfall features, or adding gentle circulation to still corners of the tank.',
    images: ['https://images.unsplash.com/photo-1499242611767-cf8b9be02854?w=900&q=80'],
    price: 24.99, currency: 'NPR',
    stockQuantity: 29, minimumStock: 8, trackInventory: true, allowBackorders: false,
    rating: { average: 4.4, count: 45 },
    attributes: [
      { label: 'Flow Rate', value: '320 GPH' }, { label: 'Material', value: 'Ceramic Shaft' },
      { label: 'Brand', value: 'ReefTech' }, { label: 'Power', value: '8W' },
    ],
    specifications: [{ label: 'Max Head Height', value: '4.5 ft' }],
    tags: ['circulation', 'water-change'], badges: [],
    isActive: true, isFeatured: false, createdAt: '2025-08-25',
    seo: { metaTitle: 'Submersible Water Pump | AquaShop', metaDescription: 'Compact, reliable submersible pump for circulation and water changes.' },
  },

  // ───────────────────────── HEATERS ─────────────────────────
  {
    id: 'p-aquarium-heater', sku: 'HT-001', slug: 'aquarium-heater', name: 'Aquarium Heater',
    categoryId: 'cat-accessories', subcategoryId: 'cat-heaters', brand: 'ReefTech',
    shortDescription: 'Precise, shatter-resistant heating for tropical tanks.',
    description: 'An adjustable submersible heater that holds a stable temperature within half a degree, with an external dial and safety auto shut-off.',
    images: ['https://images.unsplash.com/photo-1571752726703-5e7d1f6a986d?w=900&q=80'],
    price: 22.99, currency: 'NPR',
    stockQuantity: 60, minimumStock: 12, trackInventory: true, allowBackorders: true,
    rating: { average: 4.7, count: 138 },
    attributes: [
      { label: 'Capacity', value: 'Up to 30 gal' }, { label: 'Wattage', value: '100W' },
      { label: 'Material', value: 'Shatter-resistant Quartz' }, { label: 'Brand', value: 'ReefTech' },
    ],
    specifications: [{ label: 'Temperature Range', value: '68–93°F adjustable' }],
    tags: ['tropical', 'adjustable'], badges: ['BEST SELLER'],
    isActive: true, isFeatured: true, createdAt: '2025-07-30',
    seo: { metaTitle: 'Aquarium Heater | AquaShop', metaDescription: 'Adjustable, shatter-resistant aquarium heater for stable tropical temperatures.' },
  },

  // ───────────────────────── LIGHTING ─────────────────────────
  {
    id: 'p-led-light', sku: 'LT-001', slug: 'led-aquarium-light', name: 'LED Aquarium Light',
    categoryId: 'cat-accessories', subcategoryId: 'cat-lighting', brand: 'ReefTech',
    shortDescription: 'Full-spectrum lighting that makes color and plants pop.',
    description: 'This slim LED fixture spans the full spectrum for vibrant fish color and healthy plant growth, with adjustable brightness and a built-in timer.',
    images: ['https://images.unsplash.com/photo-1544923246-77307dd654cb?w=900&q=80'],
    price: 44.99, salePrice: 36.99, currency: 'NPR',
    stockQuantity: 33, minimumStock: 8, trackInventory: true, allowBackorders: false,
    rating: { average: 4.8, count: 167 },
    attributes: [
      { label: 'Capacity', value: 'Fits 20–29 gal' }, { label: 'Spectrum', value: 'Full Spectrum' },
      { label: 'Material', value: 'Aluminum Housing' }, { label: 'Brand', value: 'ReefTech' }, { label: 'Power', value: '15W' },
    ],
    specifications: [{ label: 'Timer', value: 'Built-in 24-hour timer' }],
    tags: ['plant-growth', 'color-enhancing'], badges: ['SALE'],
    isActive: true, isFeatured: true, createdAt: '2025-10-27',
    seo: { metaTitle: 'LED Aquarium Light | AquaShop', metaDescription: 'Full-spectrum LED aquarium light with timer for plants and color.' },
  },

  // ───────────────────────── DECORATIONS ─────────────────────────
  {
    id: 'p-driftwood', sku: 'DC-001', slug: 'driftwood-decoration', name: 'Driftwood Decoration',
    categoryId: 'cat-accessories', subcategoryId: 'cat-decorations', brand: 'GreenReef',
    shortDescription: 'Natural, aquarium-safe driftwood for aquascaping and plant mounting.',
    description: 'Each piece is pre-soaked and sinks reliably, providing a natural centerpiece and an anchor point for Java Fern, Anubias, and moss.',
    images: ['https://images.unsplash.com/photo-1520301255226-bf5f144451c1?w=900&q=80'],
    price: 18.99, currency: 'NPR',
    stockQuantity: 27, minimumStock: 6, trackInventory: true, allowBackorders: true,
    rating: { average: 4.7, count: 54 },
    attributes: [
      { label: 'Material', value: 'Natural Driftwood' }, { label: 'Dimensions', value: '10–14 in' },
      { label: 'Brand', value: 'GreenReef' },
    ],
    specifications: [{ label: 'Pre-Treated', value: 'Yes — pre-soaked & sinks' }],
    tags: ['aquascape', 'plant-mounting'], badges: [],
    isActive: true, isFeatured: false, createdAt: '2025-09-08',
    seo: { metaTitle: 'Driftwood Decoration | AquaShop', metaDescription: 'Natural, pre-soaked driftwood for aquascaping and plant mounting.' },
  },
  {
    id: 'p-rock-cave', sku: 'DC-002', slug: 'aquarium-rock-cave', name: 'Aquarium Rock Cave',
    categoryId: 'cat-accessories', subcategoryId: 'cat-decorations', brand: 'GreenReef',
    shortDescription: 'A resin cave that gives shy fish a natural hideaway.',
    description: 'Textured to look like natural stone, this hollow cave gives cichlids, catfish, and shrimp a safe place to retreat and breed.',
    images: ['https://images.unsplash.com/photo-1520301255226-bf5f144451c1?w=900&q=80'],
    price: 14.49, currency: 'NPR',
    stockQuantity: 36, minimumStock: 8, trackInventory: true, allowBackorders: true,
    rating: { average: 4.5, count: 41 },
    attributes: [
      { label: 'Material', value: 'Aquarium-Safe Resin' }, { label: 'Dimensions', value: '6 x 4 x 4 in' },
      { label: 'Brand', value: 'GreenReef' },
    ],
    specifications: [{ label: 'Safe For', value: 'Freshwater & saltwater' }],
    tags: ['hideout', 'breeding'], badges: [],
    isActive: true, isFeatured: false, createdAt: '2025-06-02',
    seo: { metaTitle: 'Aquarium Rock Cave | AquaShop', metaDescription: 'Natural-look resin cave hideaway for fish and shrimp.' },
  },

  // ───────────────────────── CLEANING EQUIPMENT ─────────────────────────
  {
    id: 'p-gravel-vacuum', sku: 'CL-001', slug: 'gravel-vacuum-cleaner', name: 'Gravel Vacuum Cleaner',
    categoryId: 'cat-accessories', subcategoryId: 'cat-cleaning', brand: 'ReefTech',
    shortDescription: 'Siphon gravel debris while doing routine water changes.',
    description: 'This hand-pump gravel vacuum starts the siphon without any mouth suction, making routine water changes fast and mess-free.',
    images: ['https://images.unsplash.com/photo-1584967911318-3ce0dd6f4ca0?w=900&q=80'],
    price: 15.99, currency: 'NPR',
    stockQuantity: 48, minimumStock: 10, trackInventory: true, allowBackorders: false,
    rating: { average: 4.6, count: 112 },
    attributes: [
      { label: 'Material', value: 'Plastic' }, { label: 'Length', value: '24 in' }, { label: 'Brand', value: 'ReefTech' },
    ],
    specifications: [{ label: 'Best For', value: 'Tanks 10 gal and up' }],
    tags: ['maintenance', 'water-change'], badges: [],
    isActive: true, isFeatured: false, createdAt: '2025-05-15',
    seo: { metaTitle: 'Gravel Vacuum Cleaner | AquaShop', metaDescription: 'No-spill gravel vacuum for easy, mess-free water changes.' },
  },
  {
    id: 'p-algae-scraper', sku: 'CL-002', slug: 'magnetic-algae-scraper', name: 'Magnetic Algae Scraper',
    categoryId: 'cat-accessories', subcategoryId: 'cat-cleaning', brand: 'ReefTech',
    shortDescription: 'Clean glass from outside the tank without getting your hands wet.',
    description: 'A dual-magnet scraper glides across the glass, lifting algae with a scrubbing pad on one side and a scraper blade on the other for stubborn spots.',
    images: ['https://images.unsplash.com/photo-1584967911318-3ce0dd6f4ca0?w=900&q=80'],
    price: 11.99, currency: 'NPR',
    stockQuantity: 3, minimumStock: 8, trackInventory: true, allowBackorders: true,
    rating: { average: 4.5, count: 76 },
    attributes: [
      { label: 'Material', value: 'Magnetic Foam & Plastic' }, { label: 'Glass Thickness', value: 'Up to 0.5 in' }, { label: 'Brand', value: 'ReefTech' },
    ],
    specifications: [{ label: 'Best For', value: 'Glass tanks' }],
    tags: ['algae', 'maintenance'], badges: ['LOW STOCK'],
    isActive: true, isFeatured: false, createdAt: '2025-04-21',
    seo: { metaTitle: 'Magnetic Algae Scraper | AquaShop', metaDescription: 'Glide-clean magnetic algae scraper for glass aquariums.' },
  },
  {
    id: 'p-water-conditioner', sku: 'CL-003', slug: 'water-conditioner', name: 'Water Conditioner',
    categoryId: 'cat-accessories', subcategoryId: 'cat-cleaning', brand: 'ReefNutri',
    shortDescription: 'Instantly neutralizes chlorine and chloramine for safe tap water.',
    description: 'A few drops per gallon make tap water safe for fish instantly, neutralizing chlorine, chloramine, and heavy metals while adding a protective slime coat.',
    images: ['https://images.unsplash.com/photo-1596797882870-8c33deeaaa8e?w=900&q=80'],
    price: 9.49, currency: 'NPR',
    stockQuantity: 70, minimumStock: 15, trackInventory: true, allowBackorders: true,
    rating: { average: 4.9, count: 203 },
    attributes: [
      { label: 'Volume', value: '16.9 fl oz' }, { label: 'Treats Up To', value: '3,368 gal' }, { label: 'Brand', value: 'ReefNutri' },
    ],
    specifications: [{ label: 'Dosage', value: '1 capful per 10 gal' }],
    tags: ['water-treatment', 'essential'], badges: ['BEST SELLER'],
    isActive: true, isFeatured: true, createdAt: '2025-03-11',
    seo: { metaTitle: 'Water Conditioner | AquaShop', metaDescription: 'Instant tap water conditioner that neutralizes chlorine and chloramine.' },
  },

  // ───────────────────────── FISH CARE ─────────────────────────
  {
    id: 'p-fish-medicine', sku: 'FC-001', slug: 'ich-treatment-medicine', name: 'Ich Treatment Medicine',
    categoryId: 'cat-accessories', subcategoryId: 'cat-fish-care', brand: 'ReefNutri',
    shortDescription: 'Fast-acting treatment for white-spot disease (Ich).',
    description: 'A trusted formula that treats and helps prevent Ich (white spot disease) in freshwater aquariums, safe for use with most fish species when dosed as directed.',
    images: ['https://images.unsplash.com/photo-1522911512095-8ce38fbc37e6?w=900&q=80'],
    price: 13.99, currency: 'NPR',
    stockQuantity: 26, minimumStock: 8, trackInventory: true, allowBackorders: true,
    rating: { average: 4.5, count: 88 },
    attributes: [
      { label: 'Volume', value: '8 fl oz' }, { label: 'Treats', value: 'Ich / white spot disease' }, { label: 'Brand', value: 'ReefNutri' },
    ],
    specifications: [{ label: 'Dosage', value: '1 tsp per 10 gal, repeat per label' }],
    tags: ['medicine', 'disease-treatment'], badges: [],
    isActive: true, isFeatured: false, createdAt: '2025-04-02',
    seo: { metaTitle: 'Ich Treatment Medicine | AquaShop', metaDescription: 'Fast-acting freshwater Ich (white spot) treatment.' },
  },
  {
    id: 'p-test-kit', sku: 'FC-002', slug: 'water-test-kit', name: 'Water Test Kit',
    categoryId: 'cat-accessories', subcategoryId: 'cat-fish-care', brand: 'ReefNutri',
    shortDescription: 'Test ammonia, nitrite, nitrate, and pH in minutes.',
    description: 'A liquid-based master test kit covering the four core water parameters every aquarist should monitor, with a color chart for quick, accurate reads.',
    images: ['https://images.unsplash.com/photo-1522911512095-8ce38fbc37e6?w=900&q=80'],
    price: 24.99, currency: 'NPR',
    stockQuantity: 44, minimumStock: 10, trackInventory: true, allowBackorders: true,
    rating: { average: 4.8, count: 231 },
    attributes: [
      { label: 'Tests For', value: 'Ammonia, Nitrite, Nitrate, pH' }, { label: 'Tests Included', value: '~800' }, { label: 'Brand', value: 'ReefNutri' },
    ],
    specifications: [{ label: 'Format', value: 'Liquid reagent' }],
    tags: ['testing', 'water-quality'], badges: ['BEST SELLER'],
    isActive: true, isFeatured: true, createdAt: '2025-02-18',
    seo: { metaTitle: 'Water Test Kit | AquaShop', metaDescription: 'Liquid master test kit for ammonia, nitrite, nitrate, and pH.' },
  },
  {
    id: 'p-stress-coat', sku: 'FC-003', slug: 'stress-coat-solution', name: 'Stress Coat Solution',
    categoryId: 'cat-accessories', subcategoryId: 'cat-fish-care', brand: 'ReefNutri',
    shortDescription: 'Eases fish stress during transport, water changes, or new tank setup.',
    description: 'This aloe-based solution helps fish recover from the stress of handling, shipping, or fin damage by supporting the natural slime coat.',
    images: ['https://images.unsplash.com/photo-1522911512095-8ce38fbc37e6?w=900&q=80'],
    price: 10.99, currency: 'NPR',
    stockQuantity: 51, minimumStock: 12, trackInventory: true, allowBackorders: true,
    rating: { average: 4.7, count: 97 },
    attributes: [
      { label: 'Volume', value: '8 fl oz' }, { label: 'Key Ingredient', value: 'Aloe vera' }, { label: 'Brand', value: 'ReefNutri' },
    ],
    specifications: [{ label: 'Use Case', value: 'New fish, water changes, injuries' }],
    tags: ['stress-relief', 'new-fish'], badges: [],
    isActive: true, isFeatured: false, createdAt: '2025-01-25',
    seo: { metaTitle: 'Stress Coat Solution | AquaShop', metaDescription: 'Aloe-based stress coat solution to protect and soothe fish.' },
  },

  // Additional fish, food, and accessory items to round out the catalog
  {
    id: 'p-molly-fish', sku: 'FSH-007', slug: 'molly-fish', name: 'Molly Fish',
    categoryId: 'cat-fish', brand: 'AquaLife',
    shortDescription: 'A hardy livebearer available in black, silver, and dalmatian patterns.',
    description: 'Mollies adapt well to both fresh and slightly brackish water, making them a flexible, active addition to a community tank.',
    images: ['https://images.unsplash.com/photo-1520302519104-c452c2eddb56?w=900&q=80'],
    price: 4.99, currency: 'NPR',
    stockQuantity: 68, minimumStock: 15, trackInventory: true, allowBackorders: false,
    rating: { average: 4.6, count: 59 },
    attributes: [
      { label: 'Fish Type', value: 'Molly' }, { label: 'Size', value: '2.5 in' }, { label: 'Color', value: 'Black/Silver/Dalmatian' },
      { label: 'Water Temperature', value: '72–78°F' }, { label: 'pH', value: '7.5–8.5' },
      { label: 'Compatibility', value: 'Peaceful community' }, { label: 'Care Level', value: 'Easy' }, { label: 'Expected Lifespan', value: '3–5 years' },
    ],
    specifications: [{ label: 'Minimum Tank Size', value: '10 gal' }, { label: 'Diet', value: 'Omnivore' }],
    tags: ['livebearer', 'beginner-friendly'], badges: [],
    isActive: true, isFeatured: false, createdAt: '2025-12-30',
    seo: { metaTitle: 'Molly Fish | AquaShop', metaDescription: 'Hardy, colorful Molly fish for community aquariums.' },
  },
  {
    id: 'p-platy-fish', sku: 'FSH-008', slug: 'platy-fish', name: 'Platy Fish',
    categoryId: 'cat-fish', brand: 'AquaLife',
    shortDescription: 'A compact, colorful livebearer perfect for beginners.',
    description: 'Platies are peaceful, undemanding fish available in a rainbow of colors, doing best in small groups within a planted community tank.',
    images: ['https://images.unsplash.com/photo-1524704796725-9fc3044a58b2?w=900&q=80'],
    price: 4.49, currency: 'NPR',
    stockQuantity: 72, minimumStock: 15, trackInventory: true, allowBackorders: false,
    rating: { average: 4.7, count: 66 },
    attributes: [
      { label: 'Fish Type', value: 'Platy' }, { label: 'Size', value: '2 in' }, { label: 'Color', value: 'Assorted' },
      { label: 'Water Temperature', value: '70–78°F' }, { label: 'pH', value: '7.0–8.0' },
      { label: 'Compatibility', value: 'Peaceful community' }, { label: 'Care Level', value: 'Easy' }, { label: 'Expected Lifespan', value: '3–4 years' },
    ],
    specifications: [{ label: 'Minimum Tank Size', value: '10 gal' }, { label: 'Diet', value: 'Omnivore' }],
    tags: ['livebearer', 'beginner-friendly'], badges: ['NEW'],
    isActive: true, isFeatured: false, createdAt: '2026-02-10',
    seo: { metaTitle: 'Platy Fish | AquaShop', metaDescription: 'Colorful, easy-care Platy fish for community tanks.' },
  },
  {
    id: 'p-cichlid-pellets', sku: 'FD-005', slug: 'cichlid-pellets', name: 'Cichlid Pellets',
    categoryId: 'cat-fish-food', brand: 'ReefNutri',
    shortDescription: 'High-protein sinking pellets for cichlids and larger fish.',
    description: 'Formulated for the higher protein needs of cichlids, these sinking pellets support vibrant color and reduce aggression from underfeeding.',
    images: ['https://images.unsplash.com/photo-1596797882870-8c33deeaaa8e?w=900&q=80'],
    price: 9.99, currency: 'NPR',
    stockQuantity: 39, minimumStock: 10, trackInventory: true, allowBackorders: true,
    rating: { average: 4.6, count: 52 },
    attributes: [
      { label: 'Food Type', value: 'Sinking Pellet' }, { label: 'Weight', value: '8.5 oz' },
      { label: 'Fish Type', value: 'Cichlid' }, { label: 'Age Group', value: 'Adult' },
      { label: 'Ingredients', value: 'Fish meal, krill meal, spirulina' },
    ],
    specifications: [{ label: 'Feeding Frequency', value: '1–2x daily' }],
    tags: ['cichlid', 'high-protein'], badges: [],
    isActive: true, isFeatured: false, createdAt: '2025-09-27',
    seo: { metaTitle: 'Cichlid Pellets | AquaShop', metaDescription: 'High-protein sinking pellets formulated for cichlids.' },
  },
  {
    id: 'p-algae-wafers', sku: 'FD-006', slug: 'algae-wafers', name: 'Algae Wafers',
    categoryId: 'cat-fish-food', brand: 'ReefNutri',
    shortDescription: 'Sinking wafers for plecos, catfish, and other bottom feeders.',
    description: 'These slow-dissolving wafers deliver balanced nutrition to algae-eating bottom dwellers without clouding the water.',
    images: ['https://images.unsplash.com/photo-1596797882870-8c33deeaaa8e?w=900&q=80'],
    price: 6.99, currency: 'NPR',
    stockQuantity: 58, minimumStock: 12, trackInventory: true, allowBackorders: true,
    rating: { average: 4.7, count: 84 },
    attributes: [
      { label: 'Food Type', value: 'Wafer' }, { label: 'Weight', value: '5.29 oz' },
      { label: 'Fish Type', value: 'Bottom Feeders' }, { label: 'Age Group', value: 'All Life Stages' },
      { label: 'Ingredients', value: 'Spirulina, kelp, vegetable matter' },
    ],
    specifications: [{ label: 'Feeding Frequency', value: 'Daily' }],
    tags: ['bottom-feeder', 'algae-eater'], badges: [],
    isActive: true, isFeatured: false, createdAt: '2025-11-15',
    seo: { metaTitle: 'Algae Wafers | AquaShop', metaDescription: 'Sinking algae wafers for plecos, catfish, and bottom feeders.' },
  },
  {
    id: 'p-moss-ball', sku: 'PL-004', slug: 'marimo-moss-ball', name: 'Marimo Moss Ball',
    categoryId: 'cat-accessories', subcategoryId: 'cat-plants', brand: 'GreenReef',
    shortDescription: 'A living, zero-maintenance sphere of moss that filters water naturally.',
    description: 'Marimo moss balls are a unique, slow-growing algae species that help absorb nitrates and add a soft, natural touch to any tank — safe with shrimp and Betta fish.',
    images: ['https://images.unsplash.com/photo-1524683079666-091ec38e2c78?w=900&q=80'],
    price: 7.49, currency: 'NPR',
    stockQuantity: 62, minimumStock: 12, trackInventory: true, allowBackorders: true,
    rating: { average: 4.9, count: 145 },
    attributes: [
      { label: 'Light Requirement', value: 'Low–Medium' }, { label: 'Placement', value: 'Free-floating or substrate' },
      { label: 'Growth Rate', value: 'Very Slow' }, { label: 'Care Level', value: 'Easy' },
    ],
    specifications: [{ label: 'CO2 Required', value: 'No' }],
    tags: ['low-maintenance', 'shrimp-safe'], badges: ['NEW'],
    isActive: true, isFeatured: true, createdAt: '2026-02-20',
    seo: { metaTitle: 'Marimo Moss Ball | AquaShop', metaDescription: 'Living, zero-maintenance Marimo moss ball for any freshwater tank.' },
  },
  {
    id: 'p-wavemaker', sku: 'WP-002', slug: 'wavemaker-circulation-pump', name: 'Wavemaker Circulation Pump',
    categoryId: 'cat-accessories', subcategoryId: 'cat-water-pumps', brand: 'ReefTech',
    shortDescription: 'Adjustable-flow pump that eliminates dead spots in larger tanks.',
    description: 'A magnetic-mount wavemaker with adjustable flow, ideal for reef and larger freshwater tanks that need stronger circulation.',
    images: ['https://images.unsplash.com/photo-1499242611767-cf8b9be02854?w=900&q=80'],
    price: 39.99, currency: 'NPR',
    stockQuantity: 17, minimumStock: 6, trackInventory: true, allowBackorders: false,
    rating: { average: 4.5, count: 29 },
    attributes: [
      { label: 'Flow Rate', value: '800–1600 GPH adjustable' }, { label: 'Material', value: 'ABS/Magnet Mount' },
      { label: 'Brand', value: 'ReefTech' }, { label: 'Power', value: '10W' },
    ],
    specifications: [{ label: 'Mount Type', value: 'Magnetic, tool-free' }],
    tags: ['circulation', 'reef-ready'], badges: [],
    isActive: true, isFeatured: false, createdAt: '2025-10-05',
    seo: { metaTitle: 'Wavemaker Circulation Pump | AquaShop', metaDescription: 'Adjustable magnetic wavemaker pump for stronger tank circulation.' },
  },
  {
    id: 'p-mini-heater', sku: 'HT-002', slug: 'mini-nano-heater', name: 'Mini Nano Heater',
    categoryId: 'cat-accessories', subcategoryId: 'cat-heaters', brand: 'ReefTech',
    shortDescription: 'A compact, preset heater built for tanks under 10 gallons.',
    description: 'Sized for nano tanks, this preset heater holds a stable 78°F without a bulky external controller, perfect for a single Betta setup.',
    images: ['https://images.unsplash.com/photo-1571752726703-5e7d1f6a986d?w=900&q=80'],
    price: 14.99, currency: 'NPR',
    stockQuantity: 43, minimumStock: 10, trackInventory: true, allowBackorders: true,
    rating: { average: 4.4, count: 37 },
    attributes: [
      { label: 'Capacity', value: 'Up to 10 gal' }, { label: 'Wattage', value: '25W' },
      { label: 'Material', value: 'Plastic Housing' }, { label: 'Brand', value: 'ReefTech' },
    ],
    specifications: [{ label: 'Temperature', value: 'Preset 78°F' }],
    tags: ['nano', 'preset'], badges: [],
    isActive: true, isFeatured: false, createdAt: '2025-12-12',
    seo: { metaTitle: 'Mini Nano Heater | AquaShop', metaDescription: 'Compact preset heater built for nano tanks under 10 gallons.' },
  },
  {
    id: 'p-clip-light', sku: 'LT-002', slug: 'clip-on-nano-light', name: 'Clip-On Nano Light',
    categoryId: 'cat-accessories', subcategoryId: 'cat-lighting', brand: 'ReefTech',
    shortDescription: 'A flexible-arm LED light that clips onto rimless nano tanks.',
    description: 'This lightweight clip-on fixture is ideal for nano and desktop tanks, with a bendable gooseneck arm and three brightness settings.',
    images: ['https://images.unsplash.com/photo-1544923246-77307dd654cb?w=900&q=80'],
    price: 21.99, currency: 'NPR',
    stockQuantity: 25, minimumStock: 6, trackInventory: true, allowBackorders: false,
    rating: { average: 4.3, count: 22 },
    attributes: [
      { label: 'Capacity', value: 'Fits under 10 gal' }, { label: 'Spectrum', value: 'Daylight White' },
      { label: 'Material', value: 'Aluminum/Plastic' }, { label: 'Brand', value: 'ReefTech' }, { label: 'Power', value: '5W' },
    ],
    specifications: [{ label: 'Mount Type', value: 'Clip-on gooseneck' }],
    tags: ['nano', 'desktop'], badges: [],
    isActive: true, isFeatured: false, createdAt: '2025-08-31',
    seo: { metaTitle: 'Clip-On Nano Light | AquaShop', metaDescription: 'Flexible clip-on LED light for nano and desktop aquariums.' },
  },
  {
    id: 'p-background-poster', sku: 'DC-003', slug: 'aquarium-background-poster', name: 'Aquarium Background Poster',
    categoryId: 'cat-accessories', subcategoryId: 'cat-decorations', brand: 'GreenReef',
    shortDescription: 'A double-sided ocean and jungle scene that adheres to the back of the tank.',
    description: 'This vinyl background instantly adds depth and color, hiding tank equipment behind an underwater scene visible from any angle.',
    images: ['https://images.unsplash.com/photo-1520301255226-bf5f144451c1?w=900&q=80'],
    price: 8.99, currency: 'NPR',
    stockQuantity: 40, minimumStock: 10, trackInventory: true, allowBackorders: true,
    rating: { average: 4.2, count: 28 },
    attributes: [
      { label: 'Material', value: 'Vinyl' }, { label: 'Dimensions', value: '48 x 20 in' }, { label: 'Brand', value: 'GreenReef' },
    ],
    specifications: [{ label: 'Sides', value: 'Double-sided design' }],
    tags: ['background', 'decorative'], badges: [],
    isActive: true, isFeatured: false, createdAt: '2025-07-12',
    seo: { metaTitle: 'Aquarium Background Poster | AquaShop', metaDescription: 'Double-sided vinyl background poster for a natural aquarium scene.' },
  },
  {
    id: 'p-fish-net', sku: 'CL-004', slug: 'fine-mesh-fish-net', name: 'Fine Mesh Fish Net',
    categoryId: 'cat-accessories', subcategoryId: 'cat-cleaning', brand: 'ReefTech',
    shortDescription: 'A soft, fine-mesh net that\u2019s gentle on fins and scales.',
    description: 'The fine mesh and rounded frame make catching fish for water changes or tank transfers quick and stress-free.',
    images: ['https://images.unsplash.com/photo-1584967911318-3ce0dd6f4ca0?w=900&q=80'],
    price: 5.99, currency: 'NPR',
    stockQuantity: 80, minimumStock: 15, trackInventory: true, allowBackorders: true,
    rating: { average: 4.6, count: 54 },
    attributes: [
      { label: 'Material', value: 'Fine Nylon Mesh' }, { label: 'Handle Length', value: '10 in' }, { label: 'Brand', value: 'ReefTech' },
    ],
    specifications: [{ label: 'Net Size', value: '4 x 3 in' }],
    tags: ['handling', 'gentle'], badges: [],
    isActive: true, isFeatured: false, createdAt: '2025-05-05',
    seo: { metaTitle: 'Fine Mesh Fish Net | AquaShop', metaDescription: 'Soft, fine-mesh fish net gentle on fins and scales.' },
  },
];
